version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml/:/etc/prometheus/prometheus.yml
      - PROMETHEUS:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=256MB'
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mongodb_exporter:
    image: percona/mongodb_exporter:0.20
    command:
      - '--mongodb.uri=mongodb://root:example@mongo:27017'
    restart: unless-stopped

volumes:
  PROMETHEUS:
